export const permissionMap: Record<string, Record<string, "A" | "R" | "N">> = {
  นิสัย: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  สินค้า: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  กลุ่มสินค้า: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  ประเภทสินค้า: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  หน่วย: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  พนักงานขาย: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  ลูกค้า: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  ขั้นตอนการผลิต: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  ประเภทการผลิต: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  โฟลว์การผลิต: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  หมวดหมู่สินค้า: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  เพศ: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  ไลน์การผลิต: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  ประเภทการขนส่ง: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  สาเหตุของเสีย: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  สถานที่จัดเก็บ: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
  คลังสินค้า: {
    Admin: "A",
    Owner: "A",
    Manager: "A",
    Technician: "A",
    Sale: "A",
    Accounting: "A",
  },
};
